<?xml version="1.0" ?><root>
<report><version>2</version><sessionid>d77db36cefc29c167da341c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-03-19 11:54:28</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>d77db36cefc29c167da341c</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 159.88&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.7260, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>d77db36cefc29c167da341c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-03-19 11:54:31</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>d77db36cefc29c167da341c</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 159.88&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.7260, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>d77db36cefc29c167da341c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-03-19 11:54:32</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>d77db36cefc29c167da341c</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 159.88&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.7260, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>d77db36cefc29c167da341c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-03-19 11:54:32</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>d77db36cefc29c167da341c</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 159.88&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.7260, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>d77db36cefc29c167da341c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-03-19 11:55:39</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>waitstaff_situation.py:208</categoryid><desyncid>d77db36cefc29c167da341c</desyncid><systemconfig/><screenshot/><desyncdata>Exception raised while trying to run a test event in test_events.py: (AttributeError: 'NoneType' object has no attribute '_current_order')&#13;&#10;Traceback (most recent call last):&#13;&#10;Caught and logged:&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 179, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 222, in c_api_server_tick&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 517, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\time_service.py", line 117, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\scheduling.py", line 236, in simulate&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\elements.py", line 385, in _resume&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\sim.py", line 4059, in _process_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\interaction_queue.py", line 792, in process_one_interaction_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 952, in process_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 323, in remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\si_state.py", line 1151, in _remove_gen&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5553, in on_removed_from_si_state&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\super_interaction.py", line 5565, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 7849, in _exited_pipeline&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\interactions\base\interaction.py", line 6814, in _trigger_interaction_exited_pipeline_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 266, in process_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\event_testing\event_manager_service.py", line 375, in _process_test_event&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\restaurants\waitstaff_situation.py", line 208, in handle_event&#13;&#10;AttributeError: 'NoneType' object has no attribute '_current_order'rtim=0&#13;&#10;Client Session Time: 159.88&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.7260, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
<report><version>2</version><sessionid>d77db36cefc29c167da341c</sessionid><type>desync</type><sku>ea.maxis.sims4_64.15.pc</sku><createtime>2025-03-19 12:08:12</createtime><buildsignature>Local.Unknown.Unknown.1.108.335.1020-1.300.000.188.Release</buildsignature><categoryid>household_manager.py:410</categoryid><desyncid>d77db36cefc29c167da341c</desyncid><systemconfig/><screenshot/><desyncdata>[manus] household_manager failed to handle on_all_households_and_sim_infos_loaded due to exception (RuntimeError: dictionary changed size during iteration)&#13;&#10;Traceback (most recent call last):&#13;&#10;&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 130, in wrapped&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 126, in finally_wrap&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 157, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\utils.py", line 175, in wrapper&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\areaserver.py", line 383, in c_api_client_connect&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone.py", line 609, in do_zone_spin_up&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 1659, in update&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\zone_spin_up_service.py", line 292, in on_enter&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\game_services.py", line 38, in on_all_households_and_sim_infos_loaded&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Core\sims4\service_manager.py", line 454, in on_all_households_and_sim_infos_loaded&#13;&#10;  File "T:\InGame\Gameplay\Scripts\Server\sims\household_manager.py", line 410, in on_all_households_and_sim_infos_loaded&#13;&#10;RuntimeError: dictionary changed size during iterationrtim=0&#13;&#10;Client Session Time: 159.88&#13; &#10;Num Save Errors: 0&#13; &#10;Num Load Errors: 0&#13; &#10;Current Game State: 0xdd4141d5&#13; &#10;LoadingScreenActiveFlag: 1&#13; &#10;Origin Version: 12,168,0,5425&#13; &#10;Modded: False&#13; &#10;SystemInfo: Windows 10 10.0.19045 GPU: NVIDIA GeForce GTX 1080  32.0.15.7260, GUID: 31A6DF6B-79F8-11EE-8422-00E04C5662AD&#13; &#10;</desyncdata></report>
</root>